# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trade_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(940, 760)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(810, 760))
        MainWindow.setMaximumSize(QtCore.QSize(940, 760))
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.96, stop:0 rgba(0, 0, 0, 255), stop:0.948864 rgba(0, 0, 127, 255));")
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(940, 16777215))
        self.centralwidget.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.96, stop:0 rgba(0, 0, 0, 255), stop:0.948864 rgba(0, 0, 127, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 941, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.96, stop:0 rgba(0, 0, 0, 255), stop:0.948864 rgba(0, 0, 127, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_converter = QtWidgets.QGroupBox(self.frame)
        self.groupBox_converter.setGeometry(QtCore.QRect(10, 10, 471, 191))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_converter.setFont(font)
        self.groupBox_converter.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.groupBox_converter.setObjectName("groupBox_converter")
        self.dollar_rate_lable = QtWidgets.QLabel(self.groupBox_converter)
        self.dollar_rate_lable.setGeometry(QtCore.QRect(140, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.dollar_rate_lable.setFont(font)
        self.dollar_rate_lable.setStyleSheet("background: transparent;\n"
"color: rgb(0, 255, 0);")
        self.dollar_rate_lable.setObjectName("dollar_rate_lable")
        self.label_rate_doll_lable = QtWidgets.QLabel(self.groupBox_converter)
        self.label_rate_doll_lable.setGeometry(QtCore.QRect(20, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_rate_doll_lable.setFont(font)
        self.label_rate_doll_lable.setStyleSheet("background: transparent;")
        self.label_rate_doll_lable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_rate_doll_lable.setScaledContents(True)
        self.label_rate_doll_lable.setWordWrap(False)
        self.label_rate_doll_lable.setObjectName("label_rate_doll_lable")
        self.taking_dollar = QtWidgets.QGroupBox(self.groupBox_converter)
        self.taking_dollar.setGeometry(QtCore.QRect(10, 120, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.taking_dollar.setFont(font)
        self.taking_dollar.setObjectName("taking_dollar")
        self.input_rub = QtWidgets.QLineEdit(self.taking_dollar)
        self.input_rub.setGeometry(QtCore.QRect(10, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.input_rub.setFont(font)
        self.input_rub.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_rub.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.input_rub.setObjectName("input_rub")
        self.rec_dollar = QtWidgets.QLineEdit(self.taking_dollar)
        self.rec_dollar.setGeometry(QtCore.QRect(120, 20, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rec_dollar.setFont(font)
        self.rec_dollar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.rec_dollar.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.rec_dollar.setReadOnly(True)
        self.rec_dollar.setObjectName("rec_dollar")
        self.equally_dollar_lable = QtWidgets.QLabel(self.taking_dollar)
        self.equally_dollar_lable.setGeometry(QtCore.QRect(100, 20, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.equally_dollar_lable.setFont(font)
        self.equally_dollar_lable.setStyleSheet("background: transparent;\n"
"")
        self.equally_dollar_lable.setObjectName("equally_dollar_lable")
        self.taking_rub = QtWidgets.QGroupBox(self.groupBox_converter)
        self.taking_rub.setGeometry(QtCore.QRect(10, 70, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.taking_rub.setFont(font)
        self.taking_rub.setStyleSheet("")
        self.taking_rub.setObjectName("taking_rub")
        self.equally_rub_lable = QtWidgets.QLabel(self.taking_rub)
        self.equally_rub_lable.setGeometry(QtCore.QRect(100, 20, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.equally_rub_lable.setFont(font)
        self.equally_rub_lable.setStyleSheet("background: transparent;\n"
"\n"
"")
        self.equally_rub_lable.setObjectName("equally_rub_lable")
        self.input_dollar = QtWidgets.QLineEdit(self.taking_rub)
        self.input_dollar.setGeometry(QtCore.QRect(10, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.input_dollar.setFont(font)
        self.input_dollar.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_dollar.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.input_dollar.setText("")
        self.input_dollar.setCursorPosition(0)
        self.input_dollar.setReadOnly(False)
        self.input_dollar.setObjectName("input_dollar")
        self.rec_rub = QtWidgets.QLineEdit(self.taking_rub)
        self.rec_rub.setGeometry(QtCore.QRect(120, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.rec_rub.setFont(font)
        self.rec_rub.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.rec_rub.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.rec_rub.setText("")
        self.rec_rub.setReadOnly(True)
        self.rec_rub.setObjectName("rec_rub")
        self.taking_steam = QtWidgets.QGroupBox(self.groupBox_converter)
        self.taking_steam.setGeometry(QtCore.QRect(240, 120, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.taking_steam.setFont(font)
        self.taking_steam.setObjectName("taking_steam")
        self.equally_steam_lable = QtWidgets.QLabel(self.taking_steam)
        self.equally_steam_lable.setGeometry(QtCore.QRect(100, 20, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.equally_steam_lable.setFont(font)
        self.equally_steam_lable.setStyleSheet("background: transparent;\n"
"")
        self.equally_steam_lable.setObjectName("equally_steam_lable")
        self.input_steam = QtWidgets.QLineEdit(self.taking_steam)
        self.input_steam.setGeometry(QtCore.QRect(10, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.input_steam.setFont(font)
        self.input_steam.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_steam.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.input_steam.setReadOnly(False)
        self.input_steam.setObjectName("input_steam")
        self.rec_steam = QtWidgets.QLineEdit(self.taking_steam)
        self.rec_steam.setGeometry(QtCore.QRect(120, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rec_steam.setFont(font)
        self.rec_steam.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.rec_steam.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;")
        self.rec_steam.setText("")
        self.rec_steam.setReadOnly(True)
        self.rec_steam.setObjectName("rec_steam")
        self.taking_csm = QtWidgets.QGroupBox(self.groupBox_converter)
        self.taking_csm.setGeometry(QtCore.QRect(240, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.taking_csm.setFont(font)
        self.taking_csm.setObjectName("taking_csm")
        self.equally_csm_lable = QtWidgets.QLabel(self.taking_csm)
        self.equally_csm_lable.setGeometry(QtCore.QRect(100, 20, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.equally_csm_lable.setFont(font)
        self.equally_csm_lable.setStyleSheet("background: transparent;\n"
"")
        self.equally_csm_lable.setObjectName("equally_csm_lable")
        self.input_csm = QtWidgets.QLineEdit(self.taking_csm)
        self.input_csm.setGeometry(QtCore.QRect(10, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.input_csm.setFont(font)
        self.input_csm.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_csm.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.input_csm.setReadOnly(False)
        self.input_csm.setObjectName("input_csm")
        self.rec_csm = QtWidgets.QLineEdit(self.taking_csm)
        self.rec_csm.setGeometry(QtCore.QRect(120, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rec_csm.setFont(font)
        self.rec_csm.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.rec_csm.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.rec_csm.setReadOnly(True)
        self.rec_csm.setObjectName("rec_csm")
        self.taking_dm = QtWidgets.QGroupBox(self.groupBox_converter)
        self.taking_dm.setGeometry(QtCore.QRect(240, 70, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.taking_dm.setFont(font)
        self.taking_dm.setObjectName("taking_dm")
        self.equally_dm_lable = QtWidgets.QLabel(self.taking_dm)
        self.equally_dm_lable.setGeometry(QtCore.QRect(100, 20, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.equally_dm_lable.setFont(font)
        self.equally_dm_lable.setStyleSheet("background: transparent;\n"
"")
        self.equally_dm_lable.setObjectName("equally_dm_lable")
        self.input_dm = QtWidgets.QLineEdit(self.taking_dm)
        self.input_dm.setGeometry(QtCore.QRect(10, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.input_dm.setFont(font)
        self.input_dm.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_dm.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;")
        self.input_dm.setReadOnly(False)
        self.input_dm.setObjectName("input_dm")
        self.rec_dm = QtWidgets.QLineEdit(self.taking_dm)
        self.rec_dm.setGeometry(QtCore.QRect(120, 20, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rec_dm.setFont(font)
        self.rec_dm.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.rec_dm.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.rec_dm.setReadOnly(True)
        self.rec_dm.setObjectName("rec_dm")
        self.groupBox_update = QtWidgets.QGroupBox(self.frame)
        self.groupBox_update.setGeometry(QtCore.QRect(700, 10, 231, 261))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_update.setFont(font)
        self.groupBox_update.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: qlineargradient(spread:pad, x1:0.21, y1:0, x2:0.262, y2:1, stop:0 rgba(100, 0, 0, 255), stop:1 rgba(54, 49, 39, 255));")
        self.groupBox_update.setObjectName("groupBox_update")
        self.btn_sm_name_item = QtWidgets.QPushButton(self.groupBox_update)
        self.btn_sm_name_item.setGeometry(QtCore.QRect(130, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sm_name_item.setFont(font)
        self.btn_sm_name_item.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 8px;\n"
"border-style: outset;\n"
"\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.btn_sm_name_item.setCheckable(False)
        self.btn_sm_name_item.setObjectName("btn_sm_name_item")
        self.btn_csm_sail = QtWidgets.QPushButton(self.groupBox_update)
        self.btn_csm_sail.setGeometry(QtCore.QRect(130, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_csm_sail.setFont(font)
        self.btn_csm_sail.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 8px;\n"
"border-style: outset;\n"
"\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.btn_csm_sail.setObjectName("btn_csm_sail")
        self.progressBar_bsteam = QtWidgets.QProgressBar(self.groupBox_update)
        self.progressBar_bsteam.setGeometry(QtCore.QRect(10, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_bsteam.setFont(font)
        self.progressBar_bsteam.setFocusPolicy(QtCore.Qt.NoFocus)
        self.progressBar_bsteam.setStyleSheet("border-radius: 8px;\n"
"selection-background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.501, y2:1, stop:0 rgba(255, 85, 1, 255), stop:1 rgba(0, 164, 0, 255));\n"
"color: rgb(170, 0, 0);")
        self.progressBar_bsteam.setProperty("value", 0)
        self.progressBar_bsteam.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_bsteam.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_bsteam.setObjectName("progressBar_bsteam")
        self.progressBar_bcsmsale = QtWidgets.QProgressBar(self.groupBox_update)
        self.progressBar_bcsmsale.setGeometry(QtCore.QRect(10, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.progressBar_bcsmsale.setFont(font)
        self.progressBar_bcsmsale.setStyleSheet("border-radius: 8px;\n"
"selection-background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.501, y2:1, stop:0 rgba(255, 85, 1, 255), stop:1 rgba(0, 164, 0, 255));\n"
"\n"
"color: rgb(170, 0, 0);")
        self.progressBar_bcsmsale.setProperty("value", 0)
        self.progressBar_bcsmsale.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_bcsmsale.setObjectName("progressBar_bcsmsale")
        self.progressBar_bdm = QtWidgets.QProgressBar(self.groupBox_update)
        self.progressBar_bdm.setGeometry(QtCore.QRect(10, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_bdm.setFont(font)
        self.progressBar_bdm.setFocusPolicy(QtCore.Qt.NoFocus)
        self.progressBar_bdm.setStyleSheet("border-radius: 8px;\n"
"selection-background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.501, y2:1, stop:0 rgba(255, 85, 1, 255), stop:1 rgba(0, 164, 0, 255));\n"
"color: rgb(170, 0, 0);")
        self.progressBar_bdm.setProperty("value", 0)
        self.progressBar_bdm.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_bdm.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_bdm.setObjectName("progressBar_bdm")
        self.btn_dm_name_item = QtWidgets.QPushButton(self.groupBox_update)
        self.btn_dm_name_item.setGeometry(QtCore.QRect(130, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dm_name_item.setFont(font)
        self.btn_dm_name_item.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 8px;\n"
"border-style: outset;\n"
"\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.btn_dm_name_item.setCheckable(False)
        self.btn_dm_name_item.setObjectName("btn_dm_name_item")
        self.btn_sm_item_nameid = QtWidgets.QPushButton(self.groupBox_update)
        self.btn_sm_item_nameid.setGeometry(QtCore.QRect(130, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sm_item_nameid.setFont(font)
        self.btn_sm_item_nameid.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 8px;\n"
"border-style: outset;\n"
"\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.btn_sm_item_nameid.setCheckable(False)
        self.btn_sm_item_nameid.setObjectName("btn_sm_item_nameid")
        self.label_sm_item_nameid = QtWidgets.QLabel(self.groupBox_update)
        self.label_sm_item_nameid.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sm_item_nameid.setFont(font)
        self.label_sm_item_nameid.setStyleSheet("border-radius: 8px;\n"
"selection-background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.501, y2:1, stop:0 rgba(255, 85, 1, 255), stop:1 rgba(0, 164, 0, 255));\n"
"padding-left: 14px;\n"
"color: rgb(0, 255, 0);")
        self.label_sm_item_nameid.setText("")
        self.label_sm_item_nameid.setObjectName("label_sm_item_nameid")
        self.label_steam_buy = QtWidgets.QLabel(self.groupBox_update)
        self.label_steam_buy.setGeometry(QtCore.QRect(10, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_steam_buy.setFont(font)
        self.label_steam_buy.setStyleSheet("border-radius: 8px;\n"
"selection-background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.501, y2:1, stop:0 rgba(255, 85, 1, 255), stop:1 rgba(0, 164, 0, 255));\n"
"padding-left: 14px;\n"
"color: rgb(0, 255, 0);")
        self.label_steam_buy.setText("")
        self.label_steam_buy.setObjectName("label_steam_buy")
        self.btn_sm_buy = QtWidgets.QPushButton(self.groupBox_update)
        self.btn_sm_buy.setGeometry(QtCore.QRect(130, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sm_buy.setFont(font)
        self.btn_sm_buy.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 8px;\n"
"border-style: outset;\n"
"\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.btn_sm_buy.setCheckable(False)
        self.btn_sm_buy.setObjectName("btn_sm_buy")
        self.groupBox_exchangers_one = QtWidgets.QGroupBox(self.frame)
        self.groupBox_exchangers_one.setGeometry(QtCore.QRect(390, 200, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_exchangers_one.setFont(font)
        self.groupBox_exchangers_one.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.groupBox_exchangers_one.setObjectName("groupBox_exchangers_one")
        self.sm_rub_ot = QtWidgets.QLineEdit(self.groupBox_exchangers_one)
        self.sm_rub_ot.setGeometry(QtCore.QRect(30, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sm_rub_ot.setFont(font)
        self.sm_rub_ot.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.sm_rub_ot.setInputMask("")
        self.sm_rub_ot.setText("")
        self.sm_rub_ot.setObjectName("sm_rub_ot")
        self.sm_rub_label = QtWidgets.QLabel(self.groupBox_exchangers_one)
        self.sm_rub_label.setGeometry(QtCore.QRect(10, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.sm_rub_label.setFont(font)
        self.sm_rub_label.setStyleSheet("background: transparent;")
        self.sm_rub_label.setObjectName("sm_rub_label")
        self.sm_rub_do = QtWidgets.QLineEdit(self.groupBox_exchangers_one)
        self.sm_rub_do.setGeometry(QtCore.QRect(30, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sm_rub_do.setFont(font)
        self.sm_rub_do.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.sm_rub_do.setInputMask("")
        self.sm_rub_do.setText("")
        self.sm_rub_do.setObjectName("sm_rub_do")
        self.groupBox_commission = QtWidgets.QGroupBox(self.frame)
        self.groupBox_commission.setGeometry(QtCore.QRect(490, 10, 101, 191))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_commission.setFont(font)
        self.groupBox_commission.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.groupBox_commission.setObjectName("groupBox_commission")
        self.com_steam_lable = QtWidgets.QLabel(self.groupBox_commission)
        self.com_steam_lable.setGeometry(QtCore.QRect(10, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.com_steam_lable.setFont(font)
        self.com_steam_lable.setStyleSheet("background: transparent;")
        self.com_steam_lable.setObjectName("com_steam_lable")
        self.com_csm_lable = QtWidgets.QLabel(self.groupBox_commission)
        self.com_csm_lable.setGeometry(QtCore.QRect(10, 20, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.com_csm_lable.setFont(font)
        self.com_csm_lable.setStyleSheet("background: transparent;")
        self.com_csm_lable.setObjectName("com_csm_lable")
        self.rec_com_steam = QtWidgets.QSpinBox(self.groupBox_commission)
        self.rec_com_steam.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rec_com_steam.setFont(font)
        self.rec_com_steam.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 6px;\n"
"font-size: 15px;\n"
"border: 2px solid #555;\n"
"border-style: outset;")
        self.rec_com_steam.setObjectName("rec_com_steam")
        self.rec_com_csm = QtWidgets.QSpinBox(self.groupBox_commission)
        self.rec_com_csm.setGeometry(QtCore.QRect(10, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rec_com_csm.setFont(font)
        self.rec_com_csm.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 6px;\n"
"font-size: 15px;\n"
"border: 2px solid #555;\n"
"border-style: outset;\n"
"\n"
"")
        self.rec_com_csm.setObjectName("rec_com_csm")
        self.com_dm_lable = QtWidgets.QLabel(self.groupBox_commission)
        self.com_dm_lable.setGeometry(QtCore.QRect(10, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.com_dm_lable.setFont(font)
        self.com_dm_lable.setStyleSheet("background: transparent;")
        self.com_dm_lable.setObjectName("com_dm_lable")
        self.rec_com_dm = QtWidgets.QSpinBox(self.groupBox_commission)
        self.rec_com_dm.setGeometry(QtCore.QRect(10, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rec_com_dm.setFont(font)
        self.rec_com_dm.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 6px;\n"
"font-size: 15px;\n"
"border: 2px solid #555;\n"
"border-style: outset;")
        self.rec_com_dm.setObjectName("rec_com_dm")
        self.groupBox_exchangers_two = QtWidgets.QGroupBox(self.frame)
        self.groupBox_exchangers_two.setGeometry(QtCore.QRect(550, 200, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_exchangers_two.setFont(font)
        self.groupBox_exchangers_two.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.groupBox_exchangers_two.setObjectName("groupBox_exchangers_two")
        self.exchangers_rub_lable = QtWidgets.QLabel(self.groupBox_exchangers_two)
        self.exchangers_rub_lable.setGeometry(QtCore.QRect(10, 30, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.exchangers_rub_lable.setFont(font)
        self.exchangers_rub_lable.setStyleSheet("background: transparent;")
        self.exchangers_rub_lable.setObjectName("exchangers_rub_lable")
        self.exchangers_rub_ot = QtWidgets.QLineEdit(self.groupBox_exchangers_two)
        self.exchangers_rub_ot.setGeometry(QtCore.QRect(20, 20, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exchangers_rub_ot.setFont(font)
        self.exchangers_rub_ot.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.exchangers_rub_ot.setInputMask("")
        self.exchangers_rub_ot.setText("")
        self.exchangers_rub_ot.setObjectName("exchangers_rub_ot")
        self.exchangers_rub_do = QtWidgets.QLineEdit(self.groupBox_exchangers_two)
        self.exchangers_rub_do.setGeometry(QtCore.QRect(20, 40, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exchangers_rub_do.setFont(font)
        self.exchangers_rub_do.setStyleSheet("color: rgb(0, 255, 0);\n"
"border-radius: 6px;\n"
"padding-left: 5px;\n"
"")
        self.exchangers_rub_do.setInputMask("")
        self.exchangers_rub_do.setText("")
        self.exchangers_rub_do.setObjectName("exchangers_rub_do")
        self.groupBox_services = QtWidgets.QGroupBox(self.frame)
        self.groupBox_services.setGeometry(QtCore.QRect(10, 200, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_services.setFont(font)
        self.groupBox_services.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.groupBox_services.setObjectName("groupBox_services")
        self.one_service = QtWidgets.QComboBox(self.groupBox_services)
        self.one_service.setGeometry(QtCore.QRect(20, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.one_service.setFont(font)
        self.one_service.setMouseTracking(False)
        self.one_service.setStyleSheet("border-radius: 6px;\n"
"padding-left: 4px;\n"
"border: 2px solid #555;\n"
"border-style: outset;\n"
"color: rgb(0, 255, 0);")
        self.one_service.setObjectName("one_service")
        self.one_service.addItem("")
        self.one_service.addItem("")
        self.one_service.addItem("")
        self.two_service = QtWidgets.QComboBox(self.groupBox_services)
        self.two_service.setGeometry(QtCore.QRect(220, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.two_service.setFont(font)
        self.two_service.setStyleSheet("border-radius: 6px;\n"
"padding-left: 4px;\n"
"border: 2px solid #555;\n"
"border-style: outset;\n"
"color: rgb(0, 255, 0);")
        self.two_service.setObjectName("two_service")
        self.two_service.addItem("")
        self.two_service.addItem("")
        self.two_service.addItem("")
        self.services_lable_1 = QtWidgets.QLabel(self.groupBox_services)
        self.services_lable_1.setGeometry(QtCore.QRect(170, 30, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.services_lable_1.setFont(font)
        self.services_lable_1.setMouseTracking(False)
        self.services_lable_1.setStyleSheet("background: transparent;\n"
"font-size: 30px;")
        self.services_lable_1.setObjectName("services_lable_1")
        self.services_lable_2 = QtWidgets.QLabel(self.groupBox_services)
        self.services_lable_2.setGeometry(QtCore.QRect(180, 30, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.services_lable_2.setFont(font)
        self.services_lable_2.setStyleSheet("background: transparent;\n"
"font-size: 30px;")
        self.services_lable_2.setObjectName("services_lable_2")
        self.groupBox_commission_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_commission_2.setGeometry(QtCore.QRect(600, 10, 91, 191))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_commission_2.setFont(font)
        self.groupBox_commission_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.groupBox_commission_2.setObjectName("groupBox_commission_2")
        self.btn_clear = QtWidgets.QPushButton(self.groupBox_commission_2)
        self.btn_clear.setGeometry(QtCore.QRect(10, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 8px;\n"
"border-style: outset;\n"
"\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_clear_2 = QtWidgets.QPushButton(self.groupBox_commission_2)
        self.btn_clear_2.setGeometry(QtCore.QRect(10, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear_2.setFont(font)
        self.btn_clear_2.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 8px;\n"
"border-style: outset;\n"
"\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.btn_clear_2.setObjectName("btn_clear_2")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(0, 270, 941, 471))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableView.setFont(font)
        self.tableView.setStyleSheet("color: rgb(255, 255, 127);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.96, stop:0 rgba(0, 0, 0, 255), stop:0.948864 rgba(0, 0, 127, 255));")
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Трейдер"))
        self.groupBox_converter.setTitle(_translate("MainWindow", "Конвертер цен"))
        self.dollar_rate_lable.setText(_translate("MainWindow", "0"))
        self.label_rate_doll_lable.setText(_translate("MainWindow", "Курс доллара:"))
        self.taking_dollar.setTitle(_translate("MainWindow", "Перевод в доллары"))
        self.input_rub.setPlaceholderText(_translate("MainWindow", "Рублей"))
        self.rec_dollar.setPlaceholderText(_translate("MainWindow", "Долларов"))
        self.equally_dollar_lable.setText(_translate("MainWindow", " ="))
        self.taking_rub.setTitle(_translate("MainWindow", "Перевод в рубли"))
        self.equally_rub_lable.setText(_translate("MainWindow", " ="))
        self.input_dollar.setPlaceholderText(_translate("MainWindow", "Долларов"))
        self.rec_rub.setPlaceholderText(_translate("MainWindow", "Рублей"))
        self.taking_steam.setTitle(_translate("MainWindow", "Продажа в Steam"))
        self.equally_steam_lable.setText(_translate("MainWindow", " ="))
        self.input_steam.setPlaceholderText(_translate("MainWindow", "Сумма"))
        self.rec_steam.setPlaceholderText(_translate("MainWindow", "Итоговая"))
        self.taking_csm.setTitle(_translate("MainWindow", "Продажа в CSMoney"))
        self.equally_csm_lable.setText(_translate("MainWindow", " ="))
        self.input_csm.setPlaceholderText(_translate("MainWindow", "Сумма"))
        self.rec_csm.setPlaceholderText(_translate("MainWindow", "Итоговая"))
        self.taking_dm.setTitle(_translate("MainWindow", "Продажа в DMarket"))
        self.equally_dm_lable.setText(_translate("MainWindow", " ="))
        self.input_dm.setPlaceholderText(_translate("MainWindow", "Сумма"))
        self.rec_dm.setPlaceholderText(_translate("MainWindow", "Итоговая"))
        self.groupBox_update.setTitle(_translate("MainWindow", "Обновление данных"))
        self.btn_sm_name_item.setText(_translate("MainWindow", "Steam"))
        self.btn_csm_sail.setText(_translate("MainWindow", "CSM sale"))
        self.progressBar_bsteam.setFormat(_translate("MainWindow", " %p%"))
        self.progressBar_bcsmsale.setFormat(_translate("MainWindow", " %p%"))
        self.progressBar_bdm.setFormat(_translate("MainWindow", " %p%"))
        self.btn_dm_name_item.setText(_translate("MainWindow", "DMarket"))
        self.btn_sm_item_nameid.setText(_translate("MainWindow", "Item nameid"))
        self.btn_sm_buy.setText(_translate("MainWindow", "Steam buy"))
        self.groupBox_exchangers_one.setTitle(_translate("MainWindow", "STEAM"))
        self.sm_rub_ot.setPlaceholderText(_translate("MainWindow", "от"))
        self.sm_rub_label.setText(_translate("MainWindow", "Р"))
        self.sm_rub_do.setPlaceholderText(_translate("MainWindow", "до"))
        self.groupBox_commission.setTitle(_translate("MainWindow", "Комиссия"))
        self.com_steam_lable.setText(_translate("MainWindow", "STEAM"))
        self.com_csm_lable.setText(_translate("MainWindow", "CSM"))
        self.com_dm_lable.setText(_translate("MainWindow", "DMarket"))
        self.groupBox_exchangers_two.setTitle(_translate("MainWindow", "CSM"))
        self.exchangers_rub_lable.setText(_translate("MainWindow", "Р"))
        self.exchangers_rub_ot.setPlaceholderText(_translate("MainWindow", "от"))
        self.exchangers_rub_do.setPlaceholderText(_translate("MainWindow", "до"))
        self.groupBox_services.setTitle(_translate("MainWindow", "Сервисы"))
        self.one_service.setItemText(0, _translate("MainWindow", "CSMoney live"))
        self.one_service.setItemText(1, _translate("MainWindow", "Steam"))
        self.one_service.setItemText(2, _translate("MainWindow", "DMarket"))
        self.two_service.setItemText(0, _translate("MainWindow", "Steam"))
        self.two_service.setItemText(1, _translate("MainWindow", "CSMoney sale"))
        self.two_service.setItemText(2, _translate("MainWindow", "DMarket"))
        self.services_lable_1.setText(_translate("MainWindow", "-"))
        self.services_lable_2.setText(_translate("MainWindow", ">"))
        self.groupBox_commission_2.setTitle(_translate("MainWindow", "Очистка"))
        self.btn_clear.setText(_translate("MainWindow", "CSMLP"))
        self.btn_clear_2.setText(_translate("MainWindow", "CSMLO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
